#! /bin/sh

. /etc/hue-shell.ini

. $INSTALLATION_PATH/base.sh

########################################################################
# Options
########################################################################

while getopts ":djts" OPT; do

  case $OPT in
    d)
      DEBUG=1
      echo "debug mode" >&2
      ;;

    j)
      JQDEBUG=1
      echo "debug mode with jq" >&2
      ;;

    s)
      JSONDEBUG=1
      echo "json debug mode" >&2
      ;;

    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;

    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;

  esac
done

shift $((OPTIND-1))

case "$1" in

  #
  # Set
  #

  set)
    shift
    hue_set $@
    ;;

  token)
    shift
    hue_set_token $@
    ;;

  transit)
    shift
    hue_set_transit $@
    ;;

  #
  # Info / debug
  #

  get)
    shift
    hue_get $@
    ;;

  alert)
    shift
    hue_alert $@
    ;;

  #
  # Stop
  #

  reset)
    hue_reset
    ;;

  stop)
    hue_stop
    ;;

  kill)
    hue_kill
    ;;

  #
  # Help
  #

  help)
    hue_help_long
    ;;

  *)
    hue_help_short
    ;;

esac
