#! /bin/sh

. /etc/hue-shell/hue-shell.conf

. $INSTALLATION_PATH/base.sh

##
# Print out a short help text.
##
_usage() {
echo 'Usage: hue <command>
  get <lights>
  help
  set <lights> <attributes>
  alert <lights>
'
}


case "$1" in

  #
  # Set
  #

  set)
    shift
    hue_set $@
    ;;

  transit)
    shift
    hue_set_transit $@
    ;;

  #
  # Info / debug
  #

  get)
    shift
    hue_get $@
    ;;

  alert)
    shift
    hue_alert $@
    ;;

  config)
    cat /etc/hue-shell/hue-shell.conf
    echo
    exit
    ;;

  #
  # Stop
  #

  reset)
    hue_reset
    ;;

  stop)
    hue_stop
    ;;

  kill)
    hue_kill
    ;;

  #
  # Help
  #

  help)
    _usage
    ;;

  *)
    _usage
    ;;

esac
