#! /bin/sh

. /etc/hue-shell/hue-shell.conf

. $INSTALLATION_PATH/base.sh


_help() {

}

_usage() {
  echo 'Usage: hue-color <option>'
}

##
# Scene: One color.
#
# - $1 = HUE
##
_all() {
  hue_stop
  hue_set all --hue $1 --sat 255 --bri 255
}

hue_stop

while true ; do
  case "$1" in
    -b|--blue)
      _all 46920
    break
    ;;

    -c|--cyan)
      _all 56100
    break
    ;;

    -g|--green)
      _all 25500
    break
    ;;

    -r|--red)
      _all 0
    break
    ;;

    -w|--white)
      _all 36210
    break
    ;;

    -y|--yellow)
      _all 12750
    break
    ;;

    *)
      _all $1
    break
    ;;

  esac
done
