#! /bin/sh

. /etc/hue-shell/hue-shell.conf

. $INSTALLATION_PATH/base.sh

##
# - 1$ = LIGHTS1
# - 2$ = LIGHTS2
# - 3$ = COLOR1
# - 4$ = COLOR2
# - 5$ = SWITCH_TIME
##
hue_pendulum() {

  hue_set $1 --hue $3 -t 5
  hue_set $2 --hue $4 -t 5
  sleep $5

  hue_set $2 --hue $3 -t 5
  hue_set $1 --hue $4 -t 5
  sleep $5
}

##
# Scene: Switch between two colors.
##

hue_stop

while true ; do
  case "$1" in

    -l1|--lights1)
      LIGHTS1=$2
      shift 2
      ;;

    -l2|--lights2)
      LIGHTS2=$2
      shift 2
      ;;

    -c1|color1)
      COLOR1=$2
      shift 2
      ;;

    -c2|color2)
      COLOR2=$2
      shift 2
      ;;

    -s|switchtime)
      SWITCH_TIME=$2
      shift 2
      ;;

    *)
      break
      ;;
  esac
done

#
# Default JSON.
#
if [ -z $LIGHTS1 ] || [ -z $LIGHTS2 ] ; then
  echo "Usage: hue-pendulum --lights1 1,2 --lights2 3,4"
  exit 1
fi

if [ -z $COLOR1 ]; then
  COLOR1='0'
fi

if [ -z $COLOR2 ]; then
  COLOR2='46920'
fi

if [ -z $SWITCH_TIME ]; then
  SWITCH_TIME='2'
fi

hue_set all --sat 255 --bri 255

hue_loop hue_pendulum $LIGHTS1 $LIGHTS2 $COLOR1 $COLOR2 $SWITCH_TIME
