#! /bin/sh

##
# hue-pendulum switches two group of lights between two colors.
##

. /etc/hue-shell/hue-shell.conf

. $INSTALLATION_PATH/base.sh

_usage() {
    echo '"hue-pendulum" switches two group of lights between two colors.

Usage: hue-pendulum <options>

Options:
    -l1, --lights1  Lights group 1 (e. g. 1,2,3)
    -l2, --lights2  Lights group 2 (e. g. 4,5,6)
    -c1, color1     Hue color value for lights group 1.
    -c2, color2     Hue color value for lights group 2.
    -s, switchtime  Time in seconds to switch between the two lights groups.
'
}

##
# - 1$ = LIGHTS1
# - 2$ = LIGHTS2
# - 3$ = COLOR1
# - 4$ = COLOR2
# - 5$ = SWITCH_TIME
##
_pendulum() {
  hue_set $1 --hue $3 -t 5
  hue_set $2 --hue $4 -t 5
  sleep $5

  hue_set $2 --hue $3 -t 5
  hue_set $1 --hue $4 -t 5
  sleep $5
}

hue_stop

while true ; do
  case "$1" in

    -l1|--lights1)
      LIGHTS1=$2
      shift 2
      ;;

    -l2|--lights2)
      LIGHTS2=$2
      shift 2
      ;;

    -c1|color1)
      COLOR1=$2
      shift 2
      ;;

    -c2|color2)
      COLOR2=$2
      shift 2
      ;;

    -s|switchtime)
      SWITCH_TIME=$2
      shift 2
      ;;

    *)
      break
      ;;
  esac
done

#
# Default JSON.
#
if [ -z $LIGHTS1 ] || [ -z $LIGHTS2 ]; then
  _usage
  exit 1
fi

if [ -z $COLOR1 ]; then
  COLOR1='0'
fi

if [ -z $COLOR2 ]; then
  COLOR2='46920'
fi

if [ -z $SWITCH_TIME ]; then
  SWITCH_TIME='2'
fi

hue_set all --sat 255 --bri 255

hue_loop _pendulum $LIGHTS1 $LIGHTS2 $COLOR1 $COLOR2 $SWITCH_TIME
