#! /bin/sh

. /etc/hue-shell/hue-shell.conf

. $INSTALLATION_PATH/base.sh

_usage() {
  echo "Usage: hue-load-scenes"

}

##
# Show available scenes.
##
_info() {
  echo "Available scenes:"
  for SCENE in $(find $SCENES_PATH -name "*.scene"); do
  local TOKEN=$(echo $SCENE | sed 's:.*/\(.*\).scene:\1:')
  echo " -> $TOKEN"
  done
}

##
# Execute scene.
#
# - $1 = SCENE_TOKEN
##
_execute() {
  local SCENE="$SCENES_PATH/$1.scene"

  hue_stop
  if [ -f "$SCENE" ]; then
    $SCENE
  else
    local DEFAULT_SCENE="$SCENES_PATH/$DEFAULT_SCENE.scene"
    $DEFAULT_SCENE
  fi
}

##
# Switch for scene functions.
##
case "$1" in

  execute)
    _execute $2
  ;;

  info)
    _info
  ;;

  stop)
    hue_stop
  ;;

  reset)
    hue_reset
  ;;

  *)
    _usage
  ;;

esac
