#! /bin/bash

hue-config

PIDS_FILE="$HOME/.hue/PIDS"

(
  while true; do
    hue-state -t 30 -h 0 7
    hue-state -t 20 -h 25000 7
  done
) &

echo $! >> $PIDS_FILE

(
  while true; do
    hue-state -t 50 -h 45000 8
    hue-state -t 20 -h 25000 8
  done
) &

echo $! >> $PIDS_FILE

# echo "To stop hue typ in any keys."

read INPUT

if [ -n "$INPUT" ]; then
( hue-stop ) > /dev/null
fi
