#! /bin/sh

. /etc/hue-shell/hue-shell.conf

. $INSTALLATION_PATH/base.sh

##
# Scene: One color.
#
# - $1 = HUE
##
hue_all() {
  hue_stop
  hue_set all --hue $1 --sat 255 --bri 255
}

hue_stop

while true ; do
  case "$1" in
    -b|--blue)
      hue_all 46920
    break
    ;;

    -c|--cyan)
      hue_all 56100
    break
    ;;

    -g|--green)
      hue_all 25500
    break
    ;;

    -r|--red)
      hue_all 0
    break
    ;;

    -w|--white)
      hue_all 36210
    break
    ;;

    -y|--yellow)
      hue_all 12750
    break
    ;;

    *)
    break
    ;;

  esac
done
