#! /bin/bash

case "$1" in
  wohnzimmer_haengelampe_1  | wohn_haenge_1 | wh1 ) echo 2;;
  wohnzimmer_haengelampe_2  | wohn_haenge_2 | wh2 ) echo 1;;
  wohnzimmer_haengelampe_3  | wohn_haenge_3 | wh3 ) echo 3;;
  wohnzimmer_ecke_einzeln   | wohn_eck_einz | wee ) echo 9;;
  wohnzimmer_schrank_links  | wschrank_li   | wsl ) echo 7;;
  wohnzimmer_schrank_rechts | wschrank_re   | wsr ) echo 8;;
  schlafzimmer_rechts_unten | schlaf_re_un  | sru ) echo 4;;
  schlafzimmer_links_oben   | schlaf_li_ob  | slo ) echo 5;;
  schlafzimmer_links_unten  | schlaf_li_un  | slu ) echo 6;;
esac

exit 0
