#! /bin/bash

case "$1" in
  rot          ) echo "-h 0 -s 255";;
  gelb         ) echo "-h 12750 -s 255";;
  dunkel_gruen ) echo "-h 25500 -s 255";;
  gruen        ) echo "-h 36210 -s 255";;
  blau         ) echo "-h 46920 -s 255";;
  lila         ) echo "-h 56100 -s 255";;
  *            ) echo "Unbekannter Farben-Parameter";;


esac

exit 0
