#! /bin/bash

VALUES=()

while getopts ":o:b:h:s:x:c:a:e:t:g:G:" OPT; do
  case $OPT in
    # on
    o)
      VALUES+=("\"on\":$OPTARG")
      ;;
    # bri
    b)
      VALUES+=("\"bri\":$OPTARG")
      ;;
    # hue
    h)
      VALUES+=("\"hue\":$OPTARG")
      ;;
    # sat
    s)
      VALUES+=("\"sat\":$OPTARG")
      ;;
    # xy
    x)
      VALUES+=("\"xy\":$OPTARG")
      ;;
    # ct
    c)
      VALUES+=("\"ct\":$OPTARG")
      ;;
    # alert
    a)
      VALUES+=("\"alert\":\"$OPTARG\"")
      ;;
    # effect
    e)
      VALUES+=("\"effect\":\"$OPTARG\"")
      ;;
    # transitiontime
    t)
      VALUES+=("\"transitiontime\":$OPTARG")
      ;;

    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

STATE=$(printf ",%s" "${VALUES[@]}")
STATE=${STATE:1}
STATE="{$STATE}"

echo $STATE

#echo $STATE | jq '.'

exit 0
