#! /bin/sh

. /etc/hue-shell.ini

. $INSTALLATION_PATH/base.sh

##
# Helper function for random breath scene.
#
# - $1 = LIGHT
# - $2 = HUE_RANGE
# - $3 = TIME_RANGE
# - $4 = BRI_RANGE
##
_hue_scene_random_breath() {
  local TRANSTIME=$(hue_range $3)
  local BRI_START=${4%%:*}
  local BRI_END=${4#*:}

  hue_set_transit $1 $TRANSTIME --hue $(hue_range $2) --bri $BRI_END --sat 255
  hue_set_transit $1 $TRANSTIME --bri $BRI_START
}

##
# Scene: Random breath.
##

hue_stop

while true ; do
  case "$1" in

    -l|--lights)
      local LIGHTS=$2
      shift 2
      ;;

    -h|--hue-range)
      local HUE_RANGE=$2
      shift 2
      ;;

    -t|--time-range)
      local TIME_RANGE=$2
      shift 2
      ;;

    -b|--bri-range|--brightness-range)
      local BRI_RANGE=$2
      shift 2
      ;;

    *)
      break
      ;;
  esac
done

#
# Default JSON.
#
if [ -z $LIGHTS ]; then

  if [ -n $ALL_LIGHTS ]; then
    LIGHTS=$ALL_LIGHTS
  else
    echo "Usage: hue-breath --lights 1,2,3 --hue-range 52000:58000 --time-range 5:15 --brightness-range 50:150"
    exit 1
  fi
fi

if [ -z $HUE_RANGE ]; then
  local HUE_RANGE='52000:58000'
fi

if [ -z $TIME_RANGE ]; then
  local TIME_RANGE='2:4'
fi

if [ -z $BRI_RANGE ]; then
  local BRI_RANGE='50:255'
fi

OLD_IFS=$IFS; IFS=","

for LIGHT in $LIGHTS ; do
  IFS=$OLD_IFS

  hue_loop _hue_scene_random_breath $LIGHT $HUE_RANGE $TIME_RANGE $BRI_RANGE
done
