#! /bin/bash

hue-config

PIDS_FILE="$HOME/.hue/PIDS"

(
  while true; do
    hue-state -h 3000 -b 100 -t 50 -G 7
    hue-state -h 40000 -b 255 -t 50 -G 7
  done
) &

echo $! >> $PIDS_FILE

read INPUT

if [ -n "$INPUT" ]; then
( hue-stop ) > /dev/null
fi
