#! /bin/sh

### BEGIN INIT INFO
# Provides:          Philips Hue Control
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Control Philips Hue lamps.
# Description:       Bash scripts to control Philips Hue lamps.
### END INIT INFO

# Author: Josef Friedrich <jf@josef-friedrich.de>

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/root/bin:/root/hue
DESC="Philips Hue Control"
NAME=huectrl
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
  start)
    huescene > /dev/null
    echo "Starting hue ctrl ..."
    ;;

  stop)
    hue stop
    echo "Stoping hue ctrl ..."
    ;;

  *)
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
esac

exit 0
