#! /bin/bash

function scene_light9 {
  hue set 9 '{"hue":0,"sat":255,"transitiontime":30}'
  sleep 4
  hue set 9 '{"sat":100,"transitiontime":40}'
  sleep 5
}

function loop {
  (
    while true; do
      eval "$*"
    done
  ) &
  echo $! >> /var/run/hue.pids
}

case "$1" in
  stop)
    hue stop
    ;;

  *)
    loop scene_light9 > /dev/null
    ;;

esac
