#! /bin/bash

function scene_light7 {
  hue set 7 '{"hue":0,"bri":255,"sat":255,"transitiontime":21}'
  sleep 2.1
  hue set 7 '{"bri":80,"transitiontime":21}'
  sleep 2.1
}

function scene_light8 {
  hue set 8 '{"hue":10639,"bri":80,"sat":255,"transitiontime":15}'
  sleep 1.5
  hue set 8 '{"bri":255,"transitiontime":15}'
  sleep 1.5
}

function scene_light9 {
  hue set 9 '{"hue":5000,"bri":255,"sat":255,"transitiontime":18}'
  sleep 1.8
  hue set 9 '{"bri":80,"transitiontime":18}'
  sleep 1.8
}

function loop {
  (
    while true; do
      eval "$*"
    done
  ) &
  echo $! >> /var/run/hue.pids
}

case "$1" in
  stop)
    hue stop
    ;;

  *)
    loop scene_light7 > /dev/null
    loop scene_light8 > /dev/null
    loop scene_light9 > /dev/null
    ;;

esac
