#! /bin/bash

source /etc/hue/hue.ini

##
# Show usage help text.
##
function _usage {
  echo "Usage: huescene
  - execute <scene>: Execute scene
  - info: Show available scenes
  - stop: Stop scene
  - help: Show this help"
}

##
# Show available scenes.
##
function _info {
  echo "Available scenes:"

  for SCENE in $(find $SCENES_PATH -name "*.scene"); do

    source $SCENE
    TOKEN=$(echo $SCENE | sed 's:.*/\(.*\).scene:\1:')
    echo "  -> $TOKEN ($TITLE: $DESCRIPTION)"

  done
}

##
# Execute scene.
##
function _execute {
  SCENE="$SCENES_PATH/$1.scene"

  hue stop

  if [ -f "$SCENE" ]; then
    $SCENE
  else
    DEFAULT_SCENE="$SCENES_PATH/$DEFAULT_SCENE.scene"

    if [ -f $DEFAULT_SCENE ]; then
      $DEFAULT_SCENE
    else
      info
    fi

  fi
}

case "$1" in

  execute)
    _execute $2
    ;;

  info)
    _info
    ;;

  stop)
    hue stop
    ;;

  reset)
    hue reset
    ;;

  help)
    _usage
    ;;

  *)
    _usage
    ;;

esac
