# Do not edit this file. It is managed by “skeleton”.
# For more informations: https://github.com/Josef-Friedrich/skeleton

test:
	@echo "PATH: $(PATH)"
	@echo
	@echo "PWD: $(shell pwd)"
	@echo

	./test/lib/skeleton.sh --test

readme:
	./test/lib/skeleton.sh --render-readme

sync_skeleton:
	mkdir -p test/lib
	wget -O test/lib/skeleton.sh https://raw.githubusercontent.com/Josef-Friedrich/skeleton.sh/master/skeleton.sh
	chmod a+x test/lib/skeleton.sh
	./test/lib/skeleton.sh --sync-skeleton

sync_dependencies:
	./test/lib/skeleton.sh --sync-dependencies

.PHONY: readme sync_dependencies sync_skeleton test
