#! /bin/sh

### BEGIN INIT INFO
# Provides:          Philips Hue Control
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Control Philips Hue lamps.
# Description:       Bash scripts to control Philips Hue lamps.
### END INIT INFO

# Author: Josef Friedrich <jf@josef-friedrich.de>

. /etc/hue-shell/hue-shell.conf

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/root/bin:/root/hue
DESC="Philips Hue Control"
NAME=hue
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
  start)
    hueload-random
    echo "Starting hue daemon ..."
    ;;

  restart)
    _hue_reset
    hueload-random
    echo "Starting hue daemon ..."
    ;;

  stop)
    _hue_reset
    echo "Stopping hue daemon ..."
    ;;

  *)
	echo "Usage: $SCRIPTNAME {start|restart|stop}" >&2
	exit 3
	;;
esac

exit 0
