#! /bin/sh

### BEGIN INIT INFO
# Provides:          Philips Hue Control
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Control Philips Hue lamps.
# Description:       Shell scripts to control Philips hue lamps.
### END INIT INFO

# Author: Josef Friedrich <jf@josef-friedrich.de>

. /etc/hue-shell/hue-shell.conf

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Hue-shell"
NAME=hue
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
	start)
		eval "$STARTUP_DAEMON"
		echo "Starting hue daemon ..."
		;;

	restart)
		_hue_reset
		eval "$STARTUP_DAEMON"
		echo "Starting hue daemon ..."
		;;

	stop)
		_hue_reset
		echo "Stopping hue daemon ..."
		;;

	*)
	echo "Usage: $SCRIPTNAME {start|restart|stop}" >&2
	exit 3
	;;
esac

exit 0

# vim: set ts=8 sw=8 sts=8 et :
# sublime: tab_size 8;