#!/bin/sh /etc/rc.common

# https://wiki.openwrt.org/doc/techref/initscripts

START=99
STOP=01

EXTRA_COMMANDS="status"
EXTRA_HELP="	status	Show status informations about the service"

_EXEC=/usr/bin/hueservice-detect-lights

start() {
	$_EXEC start
}

status() {
	$_EXEC status
}

stop() {
	$_EXEC stop
}
